### PR TITLE
zephyr: move CMake glue code for building as a module into Zephyr

### PR DESCRIPTION
**Pull request by tejlmand**
This commit moves the CMakeLists.txt glue code into the Zephyr repo.
It removes Zephyr specific patching from lfs_util.h as those are no
longer needed when moving the glue code out of the fork.

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

Extra note: This PR fixes the issue with `.travis.yml` still being present by cherry-picking the commit 6592719d28d8f3af931680cc04f77cf855a0b3b8

See more here: https://github.com/zephyrproject-rtos/littlefs/pull/7#issuecomment-1009876960

### CODE REVIEW

**Comment by tejlmand** [comment]
FYI: @de-nordic @poojamg

**Review by poojamg — APPROVED** [review]

**Review by poojamg — APPROVED** [review]

**Comment by poojamg** [comment]
@dleach02 , Please can you help with merging this code?

**Review by de-nordic — APPROVED** [review]
Looks OK

**Comment by de-nordic** [comment]
@dleach02 @carlescufi Can you look at this and the https://github.com/zephyrproject-rtos/zephyr/pull/41729?

**Comment by poojamg** [comment]
@dleach02 @carlescufi, Its been 13 days, can we move ahead with this MR and zephyrproject-rtos/zephyr#41729?

**Review by carlescufi — APPROVED** [review]

**Comment by carlescufi** [comment]
Sorry @de-nordic @poojamg and @tejlmand for the delay, this is merged now.

**Pull request merged**
